# Generated by Django 4.0.1 on 2022-01-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='djcore_authuser',
        ),
        migrations.AlterModelTable(
            name='listitem',
            table='djcore_listitem',
        ),
    ]
