name: Production Deploy
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2
      with:
        fetch-depth: ‘2’

    - name: Setting up AWS Credentials
      uses: aws-actions/configure-aws-credentials@0d9a5be0dceea74e09396820e1e522ba4a110d2f # v1.5.11
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Setup Python
      uses: actions/setup-python@70e2063f710ccef775ec81349f16fb39eecee9ef # v2.2.2
      with:
        python-version: 3.8

    # https://www.peterbe.com/plog/install-python-poetry-github-actions-faster
    - name: Load cached ~/.local
      uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 #v2.1.6
      with:
        path: ~/.local
        key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/production.yml') }}

    - name: Install poetry
      uses: snok/install-poetry@44d50c1274bf7fe0860f5c0531e36c9092c15b23 # v1.2.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      id: cache-virtualenv
      uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/production.yml') }}

    - name: Install poetry dependencies
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      run: poetry install
